### ISSUE TITLE
Topbar Bug

### ISSUE THREAD

**Issue by gustavo838383883** [WingedDash/DashBlox#10]
I have selected "original topbar" but its not working and i have turned off all other extensions that i have but its still not working and i tested with another account but it still didnt worked. And i have a sugestion and it is to you add a option "Show old roblox logo" and it would replace the roblox logo with the 2015 - 2017 one.

**Comment by WingedDash** [comment]
Hello, what browser are you on?  Do any errors occur in console when the topbar fails to load? The "Old Robux Logo" is already an option in DashBlox, unless you're talking about the green one with the classic light and blue theme, I'm likely going to add a classic theme option later on.

**Comment by gustavo838383883** [comment]
And im talking about the roblox logo not the robux icon

**Comment by gustavo838383883** [comment]
And there are no issues but i see a Games, Catalog, Develop and ROBUX right near the Discover, Avatar Shop, Create and Robux in devtools or inspect element

**Comment by WingedDash** [comment]
It sounds like you still have a different extension Installed, DashBlox doesn’t change the topbar to “Develop” or “Robux”.

**Comment by WingedDash** [comment]
Closed due to lack of information.
