### ISSUE TITLE
Weird thing with the dashblox settings

### ISSUE THREAD

**Issue by IssuePresenterandHelper** [WingedDash/DashBlox#12]
So i went into dashblox settings to make the robux logo the old one, after going back in i saw that not only the roblox "Page not found/Page deleted" thing was there, but only a 1th out of the normal amount was there, Please fix this! -MayPatootie on Roblox

**Comment by WingedDash** [comment]
Hello, could you provide more information about this? It would also be helpful if you could provide any errors that occur in console (Inspect Element > Console). Could you also provide what device you are using and what browser you are using.

**Comment by WingedDash** [comment]
I believe I have fixed this in v2.1.0, if it happens again, please open another ticket and provide more information.
