### ISSUE TITLE
my settings are not working

### ISSUE THREAD

**Issue by tester305** [WingedDash/DashBlox#16]
i did some settings on roblox and it sends me to roblox.com/tr/home but the changes don't apply and when you click dashblox it redirects you to roblox.com/tr/dashblox/settings and it's an 404 page so you have to delete the "tr"

**Comment by WingedDash** [comment]
It appears that Roblox has finally rolled out locale changes to the url. I had believed this was cancelled, but I guess not. I’ll patch this soon, for now if you want it to work as intended you’re going to need to change your language to English at the bottom of the site.

**Comment by tester305** [comment]
it fixed thank you
