### ISSUE TITLE
Waste’s suggestions

### ISSUE THREAD

**Issue by Wastedis** [WingedDash/DashBlox#4]
Add 
- rap viewer
- last online
- Embedded inventory 
- Dashblox badges / used for more then 5 months a little dashblox logo with like veteran or add testers 
- Games embedded

**Comment by WingedDash** [comment]
Thanks for the suggestions! Also last online is already a feature inside the development build.

**Comment by Wastedis** [comment]
> Thanks for the suggestions! Also last online is already a feature inside the development build.

**Comment by WingedDash** [comment]
Most of the suggestions have already been made.
